server:
  #port: 9000
  port: 30073
  
spring:
  session:
    store-type: redis
  aop:
    proxy-target-class: true
logging:
  path: /leon/logs/leon_micro/edge/
  level:
    org.springframework.security: DEBUG
    

    
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 600000

proxy:
  auth:
    routes:
      basis: oauth2
      
---
spring:
  profiles: local
  redis:
    database: 6
    host: 15.114.100.54
    port: 6379
    pool:
      max-active: 10
      max-idle: 10
      max-wait: -1
      min-idle: 0   

zuul:
  sensitive-headers: '' #Distribute headers cookies to children
  routes:
    authserver1:
      path: /uaa/**
      url: http://16.157.245.40:9009/uaa
      
  