server:
  port: 9009
  context-path: /uaa
  use-forward-headers: true
  
feign:
  hystrix:
    enabled: false

ribbon:
  ConnectTimeout: 600000
  ReadTimeout: 600000
  eureka:
    enabled: true  
  
spring:
  profiles: local
  #aop:
    #proxy-target-class: true
  jpa:
    show-sql: false
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://16.157.245.40:3306/oauth2?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: select 1
    